scripts: temporarily run LLVM snapshot only
The recent upstream changes cause builds with 5.0.0 to fail so just disable all
old versions for now. I look into a couple of proper fixes.

error: <unknown>:0:0: in function __jhash_nwords i32 (i32, i32): A call to global function 'rol32' is not supported. Please use __attribute__((always_inline) to make sure this function is inlined.

Makefile:61: recipe for target '/home/vagrant/workspace/tools/testing/selftests/bpf/test_l4lb_noinline.o' failed
make: *** [/home/vagrant/workspace/tools/testing/selftests/bpf/test_l4lb_noinline.o] Error 1

Signed-off-by: Alexander Alemayhu <alexander@alemayhu.com>